<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-08T20:16:39 IST" name="Default suite" finished-at="2022-12-08T20:17:27 IST" duration-ms="48082">
    <groups>
    </groups>
    <test started-at="2022-12-08T20:16:39 IST" name="Default test" finished-at="2022-12-08T20:17:27 IST" duration-ms="48082">
      <class name="com.Information.GetInfo_Pushpa">
        <test-method signature="Method()[pri:0, instance:com.Information.GetInfo_Pushpa@7193666c]" started-at="2022-12-08T20:16:39 IST" name="Method" finished-at="2022-12-08T20:16:43 IST" duration-ms="3961" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method -->
        <test-method signature="Method1()[pri:0, instance:com.Information.GetInfo_Pushpa@7193666c]" started-at="2022-12-08T20:16:43 IST" name="Method1" finished-at="2022-12-08T20:17:27 IST" duration-ms="44053" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [December 17, 2021 (United States)] but found [17 December 2021]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [December 17, 2021 (United States)] but found [17 December 2021]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.Information.GetInfo_Pushpa.Method1(GetInfo_Pushpa.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Method1 -->
      </class> <!-- com.Information.GetInfo_Pushpa -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
